<?php
/**
 * Created by IntelliJ IDEA.
 * User: vladislav
 * Date: 3/9/19
 * Time: 11:03 AM
 */

namespace common\controllers;

use Yii;
use yii\web\Response;

abstract class BaseApiController extends BaseController
{
	abstract function actionError( $exception = null );

	/**
	 * @param $action
	 * @return bool
	 * @throws \yii\web\BadRequestHttpException
	 */
	public function beforeAction( $action )
	{
		Yii::$app->controller->enableCsrfValidation = false;

		Yii::$app->response->format = Response::FORMAT_JSON;

		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}
}