<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "carriers".
 *
 * @property integer $id
 * @property string $name
 *
 * @property \common\models\TrainVoyage[] $trainVoyages
 * @property string $aliasModel
 */
abstract class Carrier extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'carriers';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTrainVoyages()
    {
        return $this->hasMany(\common\models\TrainVoyage::className(), ['carrier_id' => 'id']);
    }




}
