<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "stations".
 *
 * @property integer $id
 * @property string $name
 *
 * @property \common\models\TrainVoyage[] $trainVoyages
 * @property \common\models\TrainVoyage[] $trainVoyages0
 * @property string $aliasModel
 */
abstract class Station extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'stations';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTrainVoyages()
    {
        return $this->hasMany(\common\models\TrainVoyage::className(), ['station_arrival' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTrainVoyages0()
    {
        return $this->hasMany(\common\models\TrainVoyage::className(), ['station_departure' => 'id']);
    }




}
