<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "train_schedule".
 *
 * @property integer $voyage_id
 * @property integer $monday
 * @property integer $tuesday
 * @property integer $wednesday
 * @property integer $thursday
 * @property integer $friday
 * @property integer $saturday
 * @property integer $sunday
 *
 * @property \common\models\TrainVoyage $voyage
 * @property string $aliasModel
 */
abstract class TrainSchedule extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'train_schedule';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'], 'integer'],
            [['voyage_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\TrainVoyage::className(), 'targetAttribute' => ['voyage_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'voyage_id' => 'Voyage ID',
            'monday' => 'Monday',
            'tuesday' => 'Tuesday',
            'wednesday' => 'Wednesday',
            'thursday' => 'Thursday',
            'friday' => 'Friday',
            'saturday' => 'Saturday',
            'sunday' => 'Sunday',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVoyage()
    {
        return $this->hasOne(\common\models\TrainVoyage::className(), ['id' => 'voyage_id']);
    }




}
