<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "train_voyage".
 *
 * @property integer $id
 * @property integer $carrier_id
 * @property integer $station_departure
 * @property integer $station_arrival
 * @property string $time_departure
 * @property string $time_arrival
 * @property double $cost
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property \common\models\TrainSchedule $trainSchedule
 * @property \common\models\Carrier $carrier
 * @property \common\models\Station $stationArrival
 * @property \common\models\Station $stationDeparture
 * @property string $aliasModel
 */
class TrainVoyage extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'train_voyage';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['carrier_id', 'station_departure', 'station_arrival', 'time_departure', 'time_arrival', 'cost'], 'required'],
            [['carrier_id', 'station_departure', 'station_arrival'], 'integer'],
            [['cost'], 'number'],
            [['time_departure', 'time_arrival'], 'string', 'max' => 255],
            [['carrier_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Carrier::className(), 'targetAttribute' => ['carrier_id' => 'id']],
            [['station_arrival'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Station::className(), 'targetAttribute' => ['station_arrival' => 'id']],
            [['station_departure'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Station::className(), 'targetAttribute' => ['station_departure' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'carrier_id' => 'Carrier ID',
            'station_departure' => 'Station Departure',
            'station_arrival' => 'Station Arrival',
            'time_departure' => 'Time Departure',
            'time_arrival' => 'Time Arrival',
            'cost' => 'Cost',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTrainSchedule()
    {
        return $this->hasOne(\common\models\TrainSchedule::className(), ['voyage_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCarrier()
    {
        return $this->hasOne(\common\models\Carrier::className(), ['id' => 'carrier_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStationArrival()
    {
        return $this->hasOne(\common\models\Station::className(), ['id' => 'station_arrival']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStationDeparture()
    {
        return $this->hasOne(\common\models\Station::className(), ['id' => 'station_departure']);
    }




}
